### ISSUE TITLE
Comments about explanation of twist techniques (from Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#10]
Comments from Chloe (Expert Reviewer)

To help with the discussion later, you may want to add something about twists here, and something along the lines of 'it can sometimes be convenient for efficiency to do the computations of G2 in the twist Et, and so consider G2 to instead be a subgroup of Et.'

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
