### ISSUE TITLE
Comments about wording "octet string" (from Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#15]
Comments from Chloe (Expert Reviewer)

- paragraph 3: is this really called a octet string even when d != 8?

**Comment by yumi-sakemi** [comment]
Our draft uses the data conversion method for an element in extension fields in the following draft, and the term "octet string" is used, so we followed this representation.

https://tools.ietf.org/html/draft-ietf-lwig-curve-representations-09

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
