### ISSUE TITLE
Editorial comments for section 4 (from Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#18]
Comments from Chloe (Expert Reviewer)

- 'we introduce secure pairing-friendly curves' -> 'we introduce some of the known secure pairing-friendly curves'
- 'widely use' -> 'in wide use' or 'widely used' (twice)
- 'peer-reviews paper' -> 'a peer-reviewed paper' or 'peer-reviewed papers'
- 'greatly depending' -> 'greatly dependant'
- 'so we consder that viewpoint...': grammar here is strange. Suggestion: 'so we choose to prioritize "security" and "widely used" over "efficiency" in consideration of future interconnections and interoperability over the internet.'

**Comment by yumi-sakemi** [comment]
fixed the following comments when we updated from version 03 to 04.
- 'widely use' -> 'in wide use' or 'widely used' (twice)
- 'peer-reviews paper' -> 'a peer-reviewed paper' or 'peer-reviewed papers'

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
