### ISSUE TITLE
Editorial comments for section 4.1.2 (from Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#26]
Comments from Chloe (Expert Reviewer)

- paragraph 4, sen 1: 'that include' -> 'including'

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
