### ISSUE TITLE
Editorial comments for section 4.1.3 (from Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#27]
Comments from Chloe (Expert Reviewer)

- first paragraph is confusing, maybe just remove it
- par 2: 'implements' -> 'uses'; 
   'After exTNFS, they propose a new parameter of BLS12 as
   BLS12_381 [BLS12-381] and publish its experimental implementation
   [zkcrypto].'
 -> 'In response to the exTNFS attacks, they proposed new parameters using
   BLS12_381 [BLS12-381] and published its experimental implementation
   [zkcrypto].'
- par 3: 
   Ethereum 2.0 *adopted* BLS12_381 and uses *the* implementation by
   Meyer[pureGo-bls].  Chia Network *published* their implementation
   [Chia] by integrating the RELIC toolkit [RELIC].  DFINITY uses mcl
   and Algorand *published an* implementation which supports BLS12_381.

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
