### ISSUE TITLE
Comments about parameters for 100-bits of security (from Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#28]
Comments from Chloe (Expert Reviewer)

- since you are allowing 100-bits of security for certain applications, it would be relevant to include a '100-bits of security' column in Table 1.

**Comment by yumi-sakemi** [comment]
We thought that allowing the parameter of 100-bit security level would confuse the reader, so we removed the parameters when we update from draft 03 to 04.

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
