### ISSUE TITLE
About CIRCL's explanation (from Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#3]
Comments from Chloe (Expert Reviewer) 

- sen 22: the meaning here is unclear. Do you mean 'They plan to include secure pairing implementations in CIRCL' or 'They plan to include securely implemented subroutines for pairing computations on certain paring-friendly curves in CIRCL'?

**Comment by yumi-sakemi** [comment]
We revised the sentence according to the following blog post by Cloudflare.
 
https://blog.cloudflare.com/introducing-circl/

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
