### ISSUE TITLE
Editorial comments for section 5 (from Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#35]
Comments from Chloe (Expert Reviewer)

- the parameters for 100 bits of security are not given explictly (just 'less than 128'), but I think it would be good to indeed do this (as I mentioned above).

**Comment by yumi-sakemi** [comment]
We thought that allowing the parameter of 100-bit security level would confuse the reader, so we removed the parameters when we update from draft 03 to 04.

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
