### ISSUE TITLE
Editorial comments for Appendix (from Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#36]
Comments from Chloe (Expert Reviewer)

- title: 'Computing Optimal Ate Pairing' -> 'Computing the Optimal Ate Pairing' or 'Computing Optimal Ate Pairings'
- sen 1: optimal -> the optimal; subfunctions -> the subfunctions
- par 3: 'its twisted curve' -> 'its twist'; 'such isomorphism' -> 'such an isomorphism'
- par 4: 'Computation of optimal Ate pairing for BN curves uses Frobenius map'
 -> 'The computation of the optimal Ate pairing for BN curves uses the Frobenius map'
- last sentence: 'Let a Frobenius' -> 'The p-power Frobenius'; 'be' -> 'is'

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
