### ISSUE TITLE
Editorial comments for section A.2 (from Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#38]
Comments from Chloe (Expert Reviewer)

- 'of optimal Ate pairing over' -> 'of the optimal Ate pairing on'; 'an order r' -> 'a prime r' or 'the order r of G_1'

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
