### ISSUE TITLE
Editorial comments for section B (from Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#39]
Comments from Chloe (Expert Reviewer)

- sen 1: 'Optiomal Ate Pairing' -> 'the optimal Ate pairing'
- replace BN462 by BLS12_381 (in light of comments on 4.3.1).

**Comment by yumi-sakemi** [comment]
The following comment became another issue #46

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
