### ISSUE TITLE
Editorial comments for section C (from Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#40]
Comments from Chloe (Expert Reviewer)

- adapt grammar and mathematical definitions in the same way as section 4.5.

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
