### ISSUE TITLE
Editorial comments throughout the draft (from Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#41]
Comments from Chloe (Expert Reviewer)

- 'security level n bits' -> 'n-bit security level'

**Comment by yumi-sakemi** [comment]
fix this issue when we update from version 03 to 04.

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
