### ISSUE TITLE
Editorial comments for test vectors (from Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#46]
Comments from Chloe (Expert Reviewer)
-replace BN462 by BLS12_381 (in light of comments on 4.3.1).

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
This issue is unified into issue #47.
