### ISSUE TITLE
Comments about the parameters of 128-bit security level

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#47]
Discussing with Chloe (Expert Reviewer), we recommend both BLS12_381 and BN462 as parameters of 128-bit security level in considerations of the use of the future internet and the safety side.
Other related issues are summarized in this issue.

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
