### ISSUE TITLE
Add ZCash Representation for BLS12-381 (from author of draft BLS signatures)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#48]
Request from Riad (he is one of author of draft "BLS signature"):
- Add chapter of ZCash representation for BLS12-381 to draft "pairing-friendly curves"

**Comment by yumi-sakemi** [comment]
We added the ZCash serialization format for BLS12-381 to our draft.
Riad joined the authors and he prepared the basic draft.
Riad, thanks for joining and we appreciate your contribution :-)

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue!
