### ISSUE TITLE
Comments about  Abstract (from 2nd Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#49]
Comments from Chloe (Expert Reviewer)

- Pairing is a special map -> Pairings are special maps OR A pairing is a special map

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue!
