### ISSUE TITLE
Editorial comments for section 1.3 (from Expert Review) 2

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#5]
Comments from Chloe (Expert Reviewer)

- sen 3: I would split this up into two sentences, one covering 128, 192, and 256-bit security, and one saying that you will also comment on 100-bit security as this is the (not secure) security level of the pairing-friendly curves that are/were in most common use.

**Comment by yumi-sakemi** [comment]
We have revised this sentence when we update from 03 to 04.

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
