### ISSUE TITLE
Comments about  section 4.2 (from 2nd Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#52]
Comments from Chloe (Expert Reviewer)

- This sentence has slightly weird grammar so I don't fully understand what you want to say: 'Therefore, the curve of the 128-bit security level
   is often used at current, so this memo recommends both BLS12-381 and
   BN462 in consideration of the future use and the safety side.'

Do you mean:
'As curves of 128-bit security level are currently the most widely used, we recommend both BLS12-381 and BN462 in this memo in order to have a more efficient and a more prudent option respectively.'

**Comment by yumi-sakemi** [comment]
I'm sorry for my weird grammar.
I adopted it because Chloe's expression is more appropriate.

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue!
