### ISSUE TITLE
Comments about section 4.2.2  (from 2nd Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#54]
Comments from Chloe (Expert Reviewer)

- This comment could be more clearly worded:
'We have to note that the BN462 becomes slower compared to BLS12_381,
   although the BN462 is suitable for the parameters of the 128-bit
   security level for the use of the future internet.'
How about instead:
'We have to note that BN462 is significantly slower than BLS12_381,
   but has 134-bit security level [GMT19],
   so may be more resistant to future small improvements to the exTNFS attack.'

This would be a good place to also add a remark along the lines of:
'We note also that CP8_544 is more efficient than BN462, has 131-bit security level,
and that due to its construction will not be affected by future small improvements to the exTNFS attack. However, as this curve is not widely used (it is only implemented in one library), we instead chose BN462 for our 'safe' option.'

**Comment by yumi-sakemi** [comment]
I adopted Chloe's comments because it is more appropriate.

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue!
