### ISSUE TITLE
Comments about some attacks for pairing-based cryptography

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#57]
Comments from Sean Bowe:

- it's worth considering Cheon's attack and twist security -- not sure if the paper you got these parameters from did that.

**Comment by yumi-sakemi** [comment]
Thanks to his comments, I noticed that the description of the Cheon's
attack was missing from the security consideration in our draft.
The recommended curves are affected by the Cheon's attack, so I added 
it to the security consideration.

Regarding the twist security, in the case of pairing, since the
twisted curve itself is used as a G_2, the security of DLP in G_2 is
also considered.

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking, Tsunekazu!
I'll close this issue.
