### ISSUE TITLE
Add bls12377js libraies to Table1

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#58]
We plan to refer Kobi's OSS (which is published in the following GitHub page) in the version 08 of our draft as one of the adoption results of pairing-friendly curves according to Kobi's comments*1.

https://github.com/celo-org/bls12377js

*1: https://github.com/cfrg/draft-irtf-cfrg-pairing-friendly-curves/pull/56

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking, Tsunekazu!
I'll close this issue.
