### ISSUE TITLE
Comments from Armando during the RGLC (Minor Comments)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#59]
Minor comments from Armando (CFRG members) are shown as follows.

https://mailarchive.ietf.org/arch/msg/cfrg/5R3YzUekQTqpJxatVVsrksNDoms/

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
(Reply Comments)

> Section 2.2: You can start by defining what a bilinear pairing is and its properties with respect to abstract groups. 
 After that you can describe how these groups are instantiated using the torsion-r subgroups of elliptic curves.
  
 >Note the distinction between:
 F_q-rational points are those with coordinates in F_q.
 and F_q^k-rational points are those with coordinates in F_q^k.
 
  >E(F_q^k): the group of rational points of E.
  #E(F_q^k): the number of rational points of E.

Thank you for your suggestion!
I'm sorry, but I think there is not a big problem because this part has passed Expert Review.

**Comment by yumi-sakemi** [comment]
(Reply Comments)
>Both BN, BLS, and KSS are families of pairing-friendly curves. Consider to rewrite sentences like this one: "A BN curve [BN05] is one of the instantiations of pairing-friendly curves proposed in 2005".

Thank you for your comments.
We revised the part pointed out according to your comments.

**Comment by yumi-sakemi** [comment]
(Reply Comments)
>This sentence is redundant as p is prime.
  " b is an element of a multiplicative group (F_p)^* of order (p - 1)"

Thanks for your comment.
A similar comment was also made by Rene, which we have revised based on that as well.

**Comment by armfazh** [comment]
All of these comments were already addressed in v08, fell free to close this issue.
