### ISSUE TITLE
Comments about security levels for sec. 1.3 (from Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#6]
Comments from Chloe (Expert Reviewer)

- sen 3: 'We show how to evaluate the security' -> 'We list the security levels of certain pairing-friendly curves, and motivate our choices of curves'. (Or something similar. The issue here is that you do not show how to evaluate the security, nor should you since that is a whole paper on its own, namely [BD18]. What you do is give a Table where people can look up options for pairing-friendly curves of a given security level).

**Comment by yumi-sakemi** [comment]
In addition to section 1.3, we also reflect this comment to abstract.

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
