### ISSUE TITLE
Snarks applications

### ISSUE THREAD

**Issue by mratsim** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#63]
A significant amount of work is done toward researching and efficiently implementing pairing friendly curve for Snarks:

- @yelhousni BW6-761: https://eprint.iacr.org/2020/351 is implemented in
  - Celo: https://github.com/celo-org/celo-blockchain/pull/1157
  - Gnark and Gurvy: https://github.com/ConsenSys/gurvy
  - Zexe: https://github.com/scipr-lab/zexe/tree/85cac177/algebra/src
  - Constantine (WIP): https://github.com/mratsim/constantine/blob/244f5835/constantine/config/curves_declaration.nim#L167-L190

- BLS12-377 from Zexe (https://eprint.iacr.org/2018/962 cc @Pratyush) is implemented in all those libraries and also
  - https://github.com/saitima/eip1962 (@kilic)
  - https://github.com/matter-labs/eip1962 (@shamatar)
  - is a standardization target for Ethereum: https://eips.ethereum.org/EIPS/eip-1962
  - Note that the main appeal of this curve is its high order and field modulus 2-adicity for FFT in Snarks applications.

In general there is a use-case for lower security efficient zero-knowledge proofs that is the main focus of pairing implementers:
- @kobigurk WASM Snarks: https://github.com/iden3/wasmsnark
- @jon-chuang Proposal for BLS24, BLS27 and BLS48 curves to explore in Zexe: https://github.com/scipr-lab/zexe/issues/156 https://github.com/scipr-lab/zexe/issues/156
- Aztec protocol zk-rollups using BN254_Snarks in Barrentenberg: https://github.com/AztecProtocol/barretenberg.
  The Ethereum blockchain currently has too much demand and techniques that allow bundling a batch of transactions together are called rollups. This is the main scaling solution, with zk-Snarks being one possible rollup technique explored at the moment hence [EIP1962](https://github.com/matter-labs/eip1962).

I think the 1.2 section about applications of pairing friendly curves can be significantly enhanced by expanding on this area of both research and actual application.

https://www.ietf.org/archive/id/draft-irtf-cfrg-pairing-friendly-curves-08.html#name-applications-of-pairing-bas

Some examples:
- Decentralized private computations: https://github.com/scipr-lab/zexe
- Decentralized identity:
  - https://github.com/appliedzkp/semaphore,
  - https://github.com/iden3/research
- Spam protection/rate limiting for messaging: https://github.com/vacp2p/research/issues/2
- Transaction bundlings (rollups) for blockchain scalability: https://ethereum-magicians.org/t/a-rollup-centric-ethereum-roadmap/4698

**Comment by kobigurk** [comment]
Just to give proper credit, https://github.com/iden3/wasmsnark is by @jbaylina, not me :slightly_smiling_face:

**Comment by yumi-sakemi** [comment]
To @mratsim 

I'm so sorry for the late reply.

Thank you for providing the information of the use cases and implementation status of the pairing.
I think it's very valuable and I will refer to them in the section 1 and Table 1 in the next update.
