### ISSUE TITLE
Comments about definition of terminology (from Expert Review) 

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#7]
Comments from Chloe (Expert Reviewer)

- title: Curve -> Curves
- sen 3-4: replace the full stop after 'elliptic curve' by a colon; remove 'where x and y are in F_q' (this is incorrect).
- sen 5: 'Weierstrass' -> 'the Weierstrass'
- sen 6-12 are both inprecise and insufficient to define the groups needed later. 
Problems:
*O_E is not defined in any meaningful way
*We need F_(q^m) rational points, not just F_q-rational points. (e.g. m = k for G2).
*'opposite point' is not defined.
*there are three points of intersection so 'the point of intersection' could be misinterpreted.
*'Similarly, we can define 2P = P+P', I think it would not be obvious to a newcomer that this means taking the tangent line.
*r and BP should be part of the terminology
*Unless you plan an unconventional pairing, r should be the largest prime divisor (not just any).

**Comment by yumi-sakemi** [comment]
fixed the following comments when we updated from version 03 to 04.
- sen 5: 'Weierstrass' -> 'the Weierstrass'

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
