### ISSUE TITLE
Comments about explanation of pairing (from Expert Review)

### ISSUE THREAD

**Issue by yumi-sakemi** [cfrg/draft-irtf-cfrg-pairing-friendly-curves#9]
Comments from Chloe (Expert Reviewer)

- sen 1: A pairing is defined on an elliptic curve, not two different ones, just different groups of rational points of *the same curve*. This sentence could be rewritten as 'A pairing is a bilinear map defined on two subgroups of rational points of an elliptic curve'.

**Comment by Tsune3110** [comment]
OK!

This is a cross-check as a co-author.

**Comment by yumi-sakemi** [comment]
Thank you for your checking :-)
I close this issue.
